ci: Add final check

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -115,3 +115,18 @@ jobs:
         env:
           SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
           SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
+  ci-success-check:
+    needs: [sonarqube]
+    if: always()
+    permissions:
+      contents: read
+      pull-requests: read
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check test results
+        run: |
+          if [[ "${{ needs.sonarqube.result }}" != "success" ]]; then
+            echo "CI pipeline failed or was cancelled. Marking final job as failed."
+            exit 1
+          fi
+      
